language: php

dist: bionic

php:
  - 7.4

before_install:
  - echo "deb [trusted=yes] https://apt.secrethub.io stable main" | sudo tee /etc/apt/sources.list.d/secrethub.sources.list
  - sudo apt-get update && sudo apt-get install -y secrethub-cli
  - echo "UNIT_TEST_MYSQL_USERNAME=$(secrethub read coco/source-watcher/unit-test-mysql-username)" >> .env
  - echo "UNIT_TEST_MYSQL_PASSWORD=$(secrethub read coco/source-watcher/unit-test-mysql-password)" >> .env
  - echo "UNIT_TEST_MYSQL_HOST=$(secrethub read coco/source-watcher/unit-test-mysql-host)" >> .env
  - echo "UNIT_TEST_MYSQL_PORT=$(secrethub read coco/source-watcher/unit-test-mysql-port)" >> .env
  - echo "UNIT_TEST_MYSQL_DATABASE=$(secrethub read coco/source-watcher/unit-test-mysql-database)" >> .env

before_script:
  - rm -f composer.lock
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_success:
  - export CODECOV_TOKEN="ebd97fbb-5461-4c4a-8012-17cb92ceee69"
  - bash <(curl -s https://codecov.io/bash)
